# Generated by Django 5.1 on 2024-08-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blog_category_blog_likes_blog_shared_by_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('food', 'Еда'), ('life', 'Жизнь'), ('news', 'Новости'), ('travel', 'Путешествия'), ('hobby', 'Хобби')], default='life', max_length=10),
        ),
    ]
