# Generated by Django 5.1 on 2024-08-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_blog_views_alter_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='shared_by',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='sverferfwfw', max_length=100),
            preserve_default=False,
        ),
    ]
