# Generated by Django 5.0.6 on 2024-09-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_name', models.CharField(max_length=100)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
